---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    version: "0"
  name: 10-wave-10-sleep
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  template:
    metadata:
      labels:
        version: "0"
    spec:
      serviceAccountName: argocd-server
      containers:
        - name: sleep
          image: ubuntu:latest
          command:
            - /bin/sh
            - -c
            - |
              sleep 10
      restartPolicy: Never
  backoffLimit: 1
