---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 0-wave-10-sleep
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    alexander.com/version: "v1"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: 0-wave-10-wave
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 0-wave-10-wave
      annotations:
        alexander.com/version: "v1"
    spec:
      serviceAccountName: argocd-server
      containers:
        - name: sleep
          image: ubuntu:latest
          command:
            - /bin/sh
            - -c
            - |
              sleep infinity
      restartPolicy: Always