---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 0-wave-10-sleep
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    alexander.com/version: "v10"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: 0-wave-10-wave
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 0-wave-10-wave
      annotations:
        alexander.com/version: "v10"
    spec:
      serviceAccountName: argocd-server
      containers:
        - name: example-container
          image: nginx:latest
          lifecycle:
            postStart:
              exec:
                command: ["sleep", "10"]
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 1