---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 0-wave-20-sleep
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    alexander.com/version: "v2"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: 0-wave-20-wave
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 0-wave-20-wave
      annotations:
        alexander.com/version: "v2"
    spec:
      serviceAccountName: argocd-server
      containers:
        - name: example-container
          image: nginx:latest
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "sleep 30"
            failureThreshold: 1   # If the command fails, it retries only once before failing
            periodSeconds: 5      # The probe runs every 5 seconds
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10