apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/AlexanderRousseeuw/argocd-example-apps
      usernameSecret:
        name: github-creds
        key: username
      passwordSecret:
        name: github-creds
        key: password