---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 0-sync-wave
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    alexander.com/version: "v4"
spec:
  project: default
  source:
    repoURL: https://github.com/AlexanderRousseeuw/argocd-example-apps
    path: apps/0-wave
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
